server:
  port: 8010
spring:
  application:
    name: StudentService

  cloud:
   config:
     uri: http://localhost:8888

#eureka:
 # client:
  #  service-url:
   #   defaultZone: http://localhost:8051/eureka/




#.client.service-url.default-zone=http://localhost:8761/eureka